
jlink --module-path "C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib" --add-modules java.base,javafx.controls,javafx.fxml,javafx.graphics --output target\custom-javafx-runtime
jlink --module-path "C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib" --add-modules java.base,javafx.controls,javafx.fxml,javafx.graphics --output target\custom-javafx-runtime--verbose
jlink --module-path "C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib\javafx.controls.jar;C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib\javafx.fxml.jar;C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib\javafx.graphics.jar;C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib\javafx.base.jar;" --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics --output target\custom-javafx-runtime --verbose
jlink --module-path "C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib" --add-modules java.base,javafx.controls,javafx.fxml,javafx.graphics --output target\custom-javafx-runtime--verbose



jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options "--add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m" --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --module-path "C:\javafx-sdk-21\lib" --add-modules javafx.controls,javafx.fxml --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options "--add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m" --runtime-image target\custom-javafx-runtime --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options "--add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m" --runtime-image target\custom-javafx-runtime --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options "--add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m" --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --module-path "C:\Program Files\Java\jdk-17\openjfx-21.0.7_windows-x64_bin-sdk\javafx-sdk-21.0.7\lib" --add-modules javafx.controls,javafx.fxml --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options "--add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m" --runtime-image target\custom-javafx-runtime --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options "--add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m" --runtime-image target\manual-javafx-runtime --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --verbose --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options --Xmx512m --runtime-image target\custom-javafx-runtime --dest output --win-dir-chooser --win-shortcut --win-menu --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options --Xmx512m --runtime-image target\custom-javafx-runtime --dest output --win-dir-chooser --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options '-–add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m' --runtime-image target\custom-javafx-runtime --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --win-console
jpackage --input target --name LifeTips --main-jar ui-1.0-SNAPSHOT.jar --main-class com.example.ui.Main --type exe --java-options "--add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED -Dprism.order=sw -Xmx512m" --runtime-image target\custom-javafx-runtime --dest debug-output --win-dir-chooser --icon "C:\Code\chaythue\web-app-share-tipsPhanMinhHieu\fe-pc\ui\icon.ico" --module-path "C:\javafx-sdk-21\lib" --add-modules javafx.controls,javafx.fxml --win-console

